security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            entry_point: form_login
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                username_parameter: _username
                password_parameter: _password
                default_target_path: app_dashboard
                failure_path: app_login
                failure_forward: false
            oauth:
                resource_owners:
                    google: "/oauth/check-google"
                login_path: /login
                failure_path: /login
              #  oauth_success_handler: App\Security\OAuthAuthenticationSuccessHandler
              #  user_provider: App\Security\OAuthUserProvider
                success_handler: App\Security\OAuthAuthenticationSuccessHandler
                oauth_user_provider:
                        service: App\Security\OAuthUserProvider
            logout:
                path: app_logout
                target: app_login
            user_checker: App\Security\UserChecker

    role_hierarchy:
        ROLE_ADMIN: [ ROLE_DRIVER, ROLE_TAXI, ROLE_CLIENT, ROLE_USER ]
        ROLE_DRIVER: ROLE_TAXI
        ROLE_TAXI: ROLE_CLIENT
        ROLE_CLIENT: ROLE_USER

    access_control:
        - { path: ^/reservation/pdf, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/dashboard, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin/users/edit, roles: ROLE_ADMIN }
        - { path: ^/admin/users/block, roles: ROLE_ADMIN }
        - { path: ^/admin/users/unblock, roles: ROLE_ADMIN }
        - { path: ^/driver, roles: ROLE_DRIVER }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/client, roles: ROLE_CLIENT }
        - { path: ^/avis/edit, roles:  ROLE_CLIENT }
        - { path: ^/avis/new, roles:  ROLE_CLIENT }
        - { path: ^/avis, roles: [ROLE_ADMIN, ROLE_CLIENT] }
        - { path: ^/vehicles/my-vehicle, roles: ROLE_DRIVER }



when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # bcrypt
                time_cost: 3 # argon
                memory_cost: 10 # argon
