controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# Route pour la page de connexion

app_home:
    path: /
    controller: App\Controller\HomeController::index

app_homes:
    path: /home
    controller: App\Controller\DashboardController::home

app_login: 
    path: /login
    controller: App\Controller\Auth\LoginController::index


# Route pour la d√©connexion
app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

# Route pour le dashboard du back-office
back_office_dashboard:
    path: /admin
    controller: App\Controller\BackOfficeController::dashboard

# Routes pour la gestion des taxis
taxi_index:
    path: /admin/taxi
    controller: App\Controller\TaxiController::index

taxi_new:
    path: /admin/taxi/new/{userId}
    controller: App\Controller\TaxiController::new
    methods: [GET,POST]
    requirements:
        userId: '\d+'

taxi_edit:
    path: /admin/taxi/{id}/edit
    controller: App\Controller\TaxiController::edit
    methods: [GET,POST]
    requirements:
        id: '\d+'

taxi_delete:
    path: /admin/taxi/{id}/delete
    controller: App\Controller\TaxiController::delete

taxi_rate:
    path: /user/taxi/{id}/rate
    controller: App\Controller\RatingController::rateTaxi
# Routes pour la gestion des courses
course_index:
    path: /admin/course
    controller: App\Controller\CourseController::index

course_show:
    path: /user/course
    controller: App\Controller\UserCourseController::index

course_new:
    path: /course/new
    controller: App\Controller\CourseController::new

user_course_new:
    path: /user/course/new
    controller: App\Controller\UserCourseController::new

course_edit:
    path: /admin/course/{id}/edit
    controller: App\Controller\CourseController::edit

course_delete:
    path: /admin/course/{id}/delete
    controller: App\Controller\CourseController::delete

course_cancel:
    path: /user/course/{id}/cancel
    controller: App\Controller\UserCourseController::cancel
# Routes pour la gestion des utilisateurs


app_dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index

admin_dashboard:
    path: /admin/dashboard
    controller: App\Controller\DashboardController::adminDashboard

admin_user_delete:
    path: /admin/users/delete
    controller: App\Controller\Admin\UserManagementController::deleteUsers

admin_user_confirm_delete:
    path: /admin/users/delete/confirm/{id}
    controller: App\Controller\Admin\UserManagementController::confirmDelete

admin_user_perform_delete:
    path: /admin/users/delete/{id}
    controller: App\Controller\Admin\UserManagementController::performDelete
    methods: POST

admin_user_edit:
    path: /admin/users/edit/{id}
    controller: App\Controller\Admin\UserManagementController::editUser
    methods: ['GET', 'POST']

app_forgot_password_request:
    path: /reset-password
    controller: App\Controller\Auth\ResetPasswordController::request
    methods: ['GET', 'POST']

app_verify_code:
    path: /reset-password/verify
    controller: App\Controller\Auth\ResetPasswordController::verifyCode
    methods: ['GET', 'POST']

app_reset_password:
    path: /reset-password/reset/{code}
    controller: App\Controller\Auth\ResetPasswordController::reset
    methods: ['GET', 'POST']
    requirements:
        code: '\d+'

test_email:
    path: /test/email
    controller: App\Controller\TestEmailController::testEmail

admin_user_block:
    path: /admin/users/block/{id}
    controller: App\Controller\Admin\UserManagementController::blockUser
    methods: POST

admin_user_unblock:
    path: /admin/users/unblock/{id}
    controller: App\Controller\Admin\UserManagementController::unblockUser
    methods: POST

admin_user_manage:
    path: /admin/users/manage
    controller: App\Controller\Admin\UserManagementController::manageUsers

driver_dashboard:
    path: /driver/dashboard
    controller: App\Controller\Driver\DashboardController::index

taxi_dashboard:
    path: /taxi/dashboard
    controller: App\Controller\TaxisteController::dashboard

client_profile:
    path: /profile
    controller: App\Controller\ProfileController::index

client_dashboard:
    path: /hello
    controller: App\Controller\Client\HelloController::index
    
taxiste_dashboard:
    path: /taxiste/dashboard
    controller: App\Controller\TaxisteController::dashboard

course_map:
    path: /admin/course/zones
    controller: App\Controller\CourseController::zonesMap

course_stats:
    path: /admin/course/stats
    controller: App\Controller\CourseController::stats
my_profile:
    path: /profile/myprofile
    controller: App\Controller\ProfileController::myProfile
urban_talk:
    path: /urban-talk
    controller: App\Controller\UrbanTalkController::chat
    methods: POST

vehicle_index:
    path: /vehicles
    controller: App\Controller\VehicleController::index

vehicle_new:
    path: /vehicles/new
    controller: App\Controller\VehicleController::new

vehicle_edit:
    path: /vehicles/edit/{id}
    controller: App\Controller\VehicleController::edit
    methods: ['GET', 'POST']

vehicle_show:
    path: /vehicles/{id}
    controller: App\Controller\VehicleController::show
    requirements:
        id: '\d+'

vehicle_delete:
    path: /vehicles/delete/{id}
    controller: App\Controller\VehicleController::delete
    methods: POST

maintenance_index:
    path: /maintenances
    controller: App\Controller\MaintenanceController::index

maintenance_show:
    path: /maintenances/{id}
    controller: App\Controller\MaintenanceController::show
    requirements:
        id: '\d+'

maintenance_new:
    path: /maintenances/new
    controller: App\Controller\MaintenanceController::create
    methods: ['GET', 'POST']

maintenance_edit:
    path: /maintenances/edit/{id}
    controller: App\Controller\MaintenanceController::update
    methods: ['GET', 'POST']

maintenance_delete:
    path: /maintenances/delete/{id}
    controller: App\Controller\MaintenanceController::delete
    methods: POST

maintenance_by_vehicle:
    path: /maintenances/vehicle/{vehicleId}
    controller: App\Controller\MaintenanceController::findByVehicleId
    
# config/routes/telegram.yaml
telegram_webhook:
    path: /telegram/webhook
    controller: App\Controller\TelegramWebhookController::webhook


hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

oauth_check_google:
    path: /oauth/check-google
    methods: [GET]
    controller: App\Controller\SecurityController::checkGoogleCallback
